# Ansible playbook AWS - install docker
---
- name: "Copy Database properties file"
  hosts: host
  tasks:
    - name: Copy DB config file
      copy:
        src: ../demo-app-flask/.db_details
        dest: /home/ec2-user/.db_details
